# 스프링에서 어플리케이션 컨텍스트, 디스패쳐서블렛 설정해주는 것들 웬만하면 여기서 설정해주는데
# 웬만한건 디폴트로 설정이 되어 있다.(mvc:annotation 등등)
spring:
  #  mvc:
  #    static-path-pattern: /content/**
  #  static 폴더로 가는 주소값 설정, 없으면 그냥 static 아래 폴더명으로 주소값 연결
  #  그럼에도 불구, 컨트롤러가 더 빨라. 컨트롤러에 동명의 핸들러가 있으면 그쪽으로 연결됨.
  thymeleaf: # 뷰리졸버 중 하나 # 참고: cache 빼고는 다 디폴트라 안써도 됨
    check-template-location: true # 템플릿 로케이션을 확인하라..?
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource: # 히카리는 기본 세팅으로 되어있기 때문에 이렇게만 해줘도 알아서 히카리로다가 거시기 해준다.
    url: jdbc:mysql://localhost:3308/moviebunker
    username: root
    password: wncks335
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:\res_file\moviebunker
  mail:
    host: smtp.gmail.com
    port: 587
    username: sleepydog931025
    password: zdsgdvtztaeigtbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 331534589280-n8hggqoddss0te2lnt8m4ob5i9u5j9cn.apps.googleusercontent.com #아이디
            client-secret: lSUIjzBlIVt4qb4pJl3MACfh #비밀번호
            scope:
              - public-profile #프로필사진
              - email #email
          kakao:
            authorization-grant-type: authorization_code
            client-id: a182ea9a450c7fd987cb0fea99312a92 # your-client-id, 요약정보에 있는 REST API키를 넣어 준다
            client-secret: GdcuWbpUkbTgECdDdNKtIAfiRF1ndID3 #your-client-secret, 여기에 Kakao Development > 보안에 있는 Client Secret에 생성된 코드를 넣어준다
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: # 동의항목에서 필수동의로 설정했던 두 가지, 이용자로부터 받아오고자 하는 정보의 범위를 말한다.
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: Y43iUtqYUnlw_q4NW8Rn #your-client-id
            client-secret: meG6L7DaSH #your-client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            # 이용자로부터 받아오고자 하는 정보의 범위
            scope: name,profile_image
            client-name: Naver
          facebook:
            client-id: 1726792610824331 #← 요거는 테스트 앱 아이디 #337722741185819 #your-client-id
            client-secret: 648981559334f4e10438f40256e9f795 #← 요거는 테스트 앱 시크릿코드 #af3435a15ea92696a2b50887660f4581 #your-client-secret
            #redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: # 동의항목에서 필수동의로 설정했던 두 가지
              - profile_nickname
              - profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis: # mybatis 도 두줄만 ㅎㅎ
  mapper-locations: mybatis-mapper/**/*.xml # resources 폴더 아래에 mybatis-mapper 폴더 안에 폴더수 상관없이 xml파일은 전부
  type-aliases-package: com.nurim.mvbunker # parameter type 또는 Result Type 에 클래스명만 적으면 이 경로 아래에서 그 클래스(게터세터 있는)를 찾아준다.

# 톰캣 포트 변경
# 포트란?? 내컴퓨터가 아파트라면 포트는 하나의 호실.. 돌아가고 있는 어플리케이션의 주소
server:
  port: 8090 # 생략하면 8080 기본. 8080을 쓰는 어플이 많아 충돌을 염려하여 바꿔준 것

# mail sender 설정